# Fetching from TMDB website

Title, overview, release date, vote_averae,popularity

In [1]:
import pandas as pd
import requests

all_movies = []

for page in range(1, 6):   # first 5 pages = 100 movies
    url = f"https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd&page={page}"
    data = requests.get(url).json()

    all_movies.extend(data["results"])

df = pd.DataFrame(all_movies)[
    ['title','overview','release_date','vote_average','popularity']
]

df

,title,overview,release_date,vote_average,popularity
0,Over Your Dead Body,A dysfunctional couple head to a remote cabin ...,2026-04-24,6.333,5.2100
1,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-04-16,7.880,334.7747
2,Tom Clancy's Jack Ryan: Ghost War,Jack Ryan is reluctantly pulled back into espi...,2026-05-20,7.238,525.2079
3,Ladies First,An arrogant but charismatic ladies' man finds ...,2026-05-21,5.700,138.7301
4,Backrooms,A strange doorway appears in the basement of a...,2026-05-27,9.200,38.0123
...,...,...,...,...,...
95,How to Make a Killing,Disowned at birth by his obscenely wealthy fam...,2026-02-16,7.100,17.3429
96,Bugonia,Two conspiracy obsessed young men kidnap the h...,2025-10-23,7.328,14.7173
97,Killing Faith,"In the summer of 1859, a widowed physician rel...",2025-10-03,5.500,8.5086
98,The Furious,After Wang Wei's daughter is kidnapped by a cr...,2026-06-10,0.000,28.6870
99,The Carpenter's Son,A remote village in Roman-era Egypt explodes i...,2025-11-13,5.896,6.9522

In [2]:
df.shape

(100, 5)

In [3]:
df.to_csv("100_movies.csv")

In [ ]:
# 200 -> worked
# 404 -> unavailable
# 500 -> server down
# data = requests.get("https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd")

In [ ]:

# d = pd.DataFrame(data.json())
# d.shape

(20, 4)

In [ ]:
# df = pd.DataFrame(data.json()['results'])[['title','overview','release_date','vote_average','popularity']]
# df

,title,overview,release_date,vote_average,popularity
0,Over Your Dead Body,A dysfunctional couple head to a remote cabin ...,2026-04-24,6.400,5.2100
1,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-04-16,7.880,334.7747
2,Tom Clancy's Jack Ryan: Ghost War,Jack Ryan is reluctantly pulled back into espi...,2026-05-20,7.238,525.2079
3,Ladies First,An arrogant but charismatic ladies' man finds ...,2026-05-21,5.700,138.7301
4,Backrooms,A strange doorway appears in the basement of a...,2026-05-27,9.200,38.0123
5,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,8.600,402.5239
6,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,2026-04-01,7.978,387.0855
7,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,2026-04-15,8.042,802.3373
8,Mortal Kombat II,The fan favorite champions—now joined by Johnn...,2026-05-06,6.802,219.2069
9,The Mandalorian and Grogu,"The evil Empire has fallen, and Imperial warlo...",2026-05-20,6.751,192.0492
10,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,7.589,130.9118
11,Animal Farm,A group of farm animals rise up against their ...,2026-04-30,4.900,5.3990
12,Masters of the Universe,"After being separated for 15 years, the Sword ...",2026-06-03,0.000,33.8312
13,Scary Movie,Twenty-six years after outrunning a suspicious...,2026-06-03,0.000,19.1112
14,Normal,An unassuming substitute sheriff with a troubl...,2026-04-16,6.451,74.8637
15,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,2026-05-12,8.426,416.9348
16,Avatar: Fire and Ash,In the wake of the devastating war against the...,2025-12-17,7.501,159.6346
17,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,2026-06-17,0.000,23.1861
18,The Devil Wears Prada 2,Andy Sachs returns to Runway as Miranda Priest...,2026-04-29,6.600,60.1950
19,Colony,Professor Se-jeong is thrust into a bloody nig...,2026-05-21,6.400,62.4045