# Fetching from TMDB website

Title, overview, release date, vote_averae,popularity

In [ ]:
import pandas as pd
import requests

all_movies = []

for page in range(1, 6):   # first 5 pages = 100 movies
    url = f"https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd&page={page}"
    data = requests.get(url).json()

    all_movies.extend(data["results"])

df = pd.DataFrame(all_movies)[
    ['title','overview','release_date','vote_average','popularity']
]
all_movies

[{'adult': False,
  'backdrop_path': '/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg',
  'id': 1083381,
  'title': 'Backrooms',
  'original_title': 'Backrooms',
  'overview': 'A strange doorway appears in the basement of a furniture showroom.',
  'poster_path': '/vpkNMkbisv5cTaIfCzUduYzXnjb.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 9648, 878],
  'popularity': 90.5218,
  'release_date': '2026-05-27',
  'softcore': False,
  'video': False,
  'vote_average': 6.0,
  'vote_count': 30},
 {'adult': False,
  'backdrop_path': '/sb76azrAXr9U13uEQxNP5e3fujY.jpg',
  'id': 1390300,
  'title': 'Over Your Dead Body',
  'original_title': 'Over Your Dead Body',
  'overview': 'A dysfunctional couple head to a remote cabin to "reconnect", but each has secret intentions to kill the other.',
  'poster_path': '/qKEvzsSuxSXCya7aFQOeCBR9wmJ.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 35, 53],
  'popularity': 89.0469,
  'release_date': '2026-04-24',
  'softcore': False,
  'video': False,
  'vote_average': 7.4,
  'vote_count': 30},
 {'adult': False,
  'backdrop_path': '/8wIaBCeGv3UhIn5CJOWQGHT1Cif.jpg',
  'id': 1242265,
  'title': 'Fuze',
  'original_title': 'Fuze',
  'overview': 'An unexploded WWII bomb is discovered on a busy construction site in the centre of London. Chaos ensues as the military and police begin a mass evacuation against a ticking clock.',
  'poster_path': '/oMFdQE5hMJ9JjhNORegwTo0GKmh.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 80, 18, 53],
  'popularity': 52.0089,
  'release_date': '2026-03-23',
  'softcore': False,
  'video': False,
  'vote_average': 6.51,
  'vote_count': 48},
 {'adult': False,
  'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
  'id': 1339713,
  'title': 'Obsession',
  'original_title': 'Obsession',
  'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
  'poster_path': '/6X4qFYBsG3bpWDG2XIKqr04kFJa.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27],
  'popularity': 332.5643,
  'release_date': '2026-04-16',
  'softcore': False,
  'video': False,
  'vote_average': 7.917,
  'vote_count': 318},
 {'adult': False,
  'backdrop_path': '/5p6BsJtnPbglYN15MuiUEppPl0f.jpg',
  'id': 1275779,
  'title': 'Disclosure Day',
  'original_title': 'Disclosure Day',
  'overview': 'If you found out we weren’t alone, if someone showed you, proved it to you, would that frighten you?',
  'poster_path': '/3o5YPjDGDTcTDL5ftDA9NwN9dLd.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [9648, 878, 53],
  'popularity': 30.6408,
  'release_date': '2026-06-10',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/lzrFleYAVX0x6qLKOwGl16slqD9.jpg',
  'id': 898704,
  'title': 'Desert Warrior',
  'original_title': 'Desert Warrior',
  'overview': 'In 7th-century Arabia, Princess Hind becomes a warrior to defy the ruthless Emperor Kisra. Forged into a warrior and aided by legendary bandit Hanzala, Hind unites warring tribes for a last stand—the historic Battle of Dhi Qar—that will change history.',
  'poster_path': '/waxnw1NpzTPY5JkqWvu0muSopRJ.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [36, 10752, 28, 18],
  'popularity': 12.82,
  'release_date': '2026-04-23',
  'softcore': False,
  'video': False,
  'vote_average': 6.7,
  'vote_count': 7},
 {'adult': False,
  'backdrop_path': '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
  'id': 1226863,
  'title': 'The Super Mario Galaxy Movie',
  'original_title': 'The Super Mario Galaxy Movie',
  'overview': "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
  'poster_path': '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10751, 35, 12, 14, 16],
  'popularity': 335.7547,
  'release_date': '2026-04-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.0,
  'vote_count': 1987},
 {'adult': False,
  'backdrop_path': '/1yl7xmTN2iEyiD3gF8M68lBhR39.jpg',
  'id': 539745,
  'title': 'Animal Farm',
  'original_title': 'Animal Farm',
  'overview': 'A group of farm animals rise up against their neglectful owner, dreaming of equality and freedom. But as the pigs take control, the revolution turns into tyranny, with truth rewritten and dissent crushed.',
  'poster_path': '/6pzI1DIlxwAFffw9OZcG6cr031U.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [16, 35, 18, 10751, 878],
  'popularity': 43.107,
  'release_date': '2026-04-30',
  'softcore': False,
  'video': False,
  'vote_average': 4.6,
  'vote_count': 15},
 {'adult': False,
  'backdrop_path': '/coyHrYHD2xHhDoYD6o4uwoJ2o7b.jpg',
  'id': 1084244,
  'title': 'Toy Story 5',
  'original_title': 'Toy Story 5',
  'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
  'poster_path': '/dWIAOC9EKFehGs3CYvDQih3hxaG.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [16, 10751, 35, 12],
  'popularity': 41.1859,
  'release_date': '2026-06-17',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 12],
  'popularity': 351.8456,
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.634,
  'vote_count': 4218},
 {'adult': False,
  'backdrop_path': '/7OedxK0BvSKJ0ZWCPRYADViTBx6.jpg',
  'id': 1228710,
  'title': 'The Mandalorian and Grogu',
  'original_title': 'The Mandalorian and Grogu',
  'overview': 'The evil Empire has fallen, and Imperial warlords remain scattered throughout the galaxy. As the fledgling New Republic works to protect everything the Rebellion fought for, they have enlisted the help of legendary Mandalorian bounty hunter Din Djarin and his young apprentice Grogu.',
  'poster_path': '/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 12, 878],
  'popularity': 183.0244,
  'release_date': '2026-05-20',
  'softcore': False,
  'video': False,
  'vote_average': 6.8,
  'vote_count': 279},
 {'adult': False,
  'backdrop_path': '/4EAAwpylq313qrDqpCxulUrXBNF.jpg',
  'id': 931285,
  'title': 'Mortal Kombat II',
  'original_title': 'Mortal Kombat II',
  'overview': 'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.',
  'poster_path': '/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 14, 12],
  'popularity': 198.021,
  'release_date': '2026-05-06',
  'softcore': False,
  'video': False,
  'vote_average': 6.8,
  'vote_count': 319},
 {'adult': False,
  'backdrop_path': '/dd31qJxOarrHyGZwYsCzOjobQzP.jpg',
  'id': 1380291,
  'title': "Tom Clancy's Jack Ryan: Ghost War",
  'original_title': "Tom Clancy's Jack Ryan: Ghost War",
  'overview': 'Jack Ryan is reluctantly pulled back into espionage when an international covert mission unravels a deadly conspiracy. Racing against time, he joins CIA allies Mike November & James Greer and sharp MI6 officer Emma Marlowe to battle a rogue black-ops unit in a high-stakes, deeply personal fight.',
  'poster_path': '/8ehYxUh5MWE41AeE9gkHE8DKzvB.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 53],
  'popularity': 492.6586,
  'release_date': '2026-05-20',
  'softcore': False,
  'video': False,
  'vote_average': 7.214,
  'vote_count': 336},
 {'adult': False,
  'backdrop_path': '/lj6AaDqDUbzm2XJltFNHeAm2uXN.jpg',
  'id': 1273221,
  'title': 'Scary Movie',
  'original_title': 'Scary Movie',
  'overview': "Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer's crosshairs and no horror movie IP is safe.",
  'poster_path': '/2OHkZEqQL4OjYXIqWopJu0BijTD.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 27],
  'popularity': 22.044,
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
  'id': 936075,
  'title': 'Michael',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'poster_path': '/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10402, 18],
  'popularity': 121.5382,
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 7.6,
  'vote_count': 863},
 {'adult': False,
  'backdrop_path': '/bOy625BjpCskOWnx3tD09MsKVCb.jpg',
  'id': 1368881,
  'title': 'Ladies First',
  'original_title': 'Ladies First',
  'overview': "An arrogant but charismatic ladies' man finds his life of money, power and casual flings upended when he wakes up in a parallel world dominated by women.",
  'poster_path': '/kjR56Yv17pbjTVBTMjqepvcus4f.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 14],
  'popularity': 130.2431,
  'release_date': '2026-05-21',
  'softcore': False,
  'video': False,
  'vote_average': 5.862,
  'vote_count': 152},
 {'adult': False,
  'backdrop_path': '/xugEpZk9YQ0DIz1aFvH5HGkqpZK.jpg',
  'id': 1304313,
  'title': "Lee Cronin's The Mummy",
  'original_title': "Lee Cronin's The Mummy",
  'overview': 'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
  'poster_path': '/uIb9Tvae5haF0XcQBaPyufmxbb0.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 9648],
  'popularity': 699.1013,
  'release_date': '2026-04-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.05,
  'vote_count': 1301},
 {'adult': False,
  'backdrop_path': '/piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg',
  'id': 454639,
  'title': 'Masters of the Universe',
  'original_title': 'Masters of the Universe',
  'overview': 'After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.',
  'poster_path': '/nm2ianYVp7OXElUZVeeAbNTqBLr.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 14, 878],
  'popularity': 37.1087,
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 10.0,
  'vote_count': 2},
 {'adult': False,
  'backdrop_path': '/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg',
  'id': 83533,
  'title': 'Avatar: Fire and Ash',
  'original_title': 'Avatar: Fire and Ash',
  'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
  'poster_path': '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 12, 14],
  'popularity': 147.8169,
  'release_date': '2025-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 7.51,
  'vote_count': 3210},
 {'adult': False,
  'backdrop_path': '/y3fQa7pytlysovXzovpXc1OQlTW.jpg',
  'id': 1314481,
  'title': 'The Devil Wears Prada 2',
  'original_title': 'The Devil Wears Prada 2',
  'overview': "Andy Sachs returns to Runway as Miranda Priestly navigates a new media landscape and Runway's position within. The duo reconnect with former assistant Emily Charlton, now the head of a luxury brand that possesses funding which could ensure Runway's survival.",
  'poster_path': '/xTI42pmsP5EDnvsNJPEDubwWBQO.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 18],
  'popularity': 55.5996,
  'release_date': '2026-04-29',
  'softcore': False,
  'video': False,
  'vote_average': 6.637,
  'vote_count': 691},
 {'adult': False,
  'backdrop_path': '/3GwOsDWJb8Qp20ETcKaYCmj7PGy.jpg',
  'id': 1259983,
  'title': 'Guru',
  'original_title': 'Gourou',
  'overview': 'Matt, a charismatic coach, captivates crowds until he spirals into a disturbing downward spiral.',
  'poster_path': '/oy9SBxmzL6pG5Lckh9o2Wa1IWBr.jpg',
  'media_type': 'movie',
  'original_language': 'fr',
  'genre_ids': [18, 53],
  'popularity': 3.6877,
  'release_date': '2026-01-28',
  'softcore': False,
  'video': False,
  'vote_average': 6.2,
  'vote_count': 180},
 {'adult': False,
  'backdrop_path': '/rw1WmxUvmbwRsbAX12m6toIg04j.jpg',
  'id': 1325734,
  'title': 'The Drama',
  'original_title': 'The Drama',
  'overview': 'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
  'poster_path': '/89Dw1ujPlIPRLddhzNuJM4F401D.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10749, 35, 18],
  'popularity': 30.0315,
  'release_date': '2026-03-26',
  'softcore': False,
  'video': False,
  'vote_average': 6.9,
  'vote_count': 819},
 {'adult': False,
  'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
  'id': 1327819,
  'title': 'Hoppers',
  'original_title': 'Hoppers',
  'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
  'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [12, 16, 35, 10751, 878],
  'popularity': 138.0178,
  'release_date': '2026-03-04',
  'softcore': False,
  'video': False,
  'vote_average': 8.128,
  'vote_count': 1253},
 {'adult': False,
  'backdrop_path': '/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg',
  'id': 1439930,
  'title': 'The Punisher: One Last Kill',
  'original_title': 'The Punisher: One Last Kill',
  'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.',
  'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 18, 80],
  'popularity': 377.4584,
  'release_date': '2026-05-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.4,
  'vote_count': 1253},
 {'adult': False,
  'backdrop_path': '/edVIvTc8RofOTxoAZN7a5kxIAay.jpg',
  'id': 1461254,
  'title': 'Salmokji: Whispering Water',
  'original_title': '살목지',
  'overview': 'An incident unfolds when a film crew goes to a reservoir to update the road view where an unidentified figure was filmed, and they encounter something in the dark, deep waters.',
  'poster_path': '/bOl0rJ86WWxVYlQlGttHhHuYiPQ.jpg',
  'media_type': 'movie',
  'original_language': 'ko',
  'genre_ids': [27, 53],
  'popularity': 9.281,
  'release_date': '2026-04-08',
  'softcore': False,
  'video': False,
  'vote_average': 6.0,
  'vote_count': 3},
 {'adult': False,
  'backdrop_path': '/9gBWv7nDp1oiB9GqNk14ajZ8IG7.jpg',
  'id': 1428857,
  'title': 'On the Hunt',
  'original_title': 'On the Hunt',
  'overview': "An ex-special forces operative discovers her daughter has been abducted by a ruthless human trafficking ring. She launches 'hunt mode', an all-out mission to bring her home. Aided by a former military comrade, she navigates the criminal underworld, unearthing a web of corruption extending from the streets of Los Angeles to high-powered officials.",
  'poster_path': '/gkscqnZZrCT5lLsniw1KNL9iiJ0.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 53],
  'popularity': 8.3175,
  'release_date': '2026-02-27',
  'softcore': False,
  'video': False,
  'vote_average': 4.571,
  'vote_count': 7},
 {'adult': False,
  'backdrop_path': '/hl7FEzMqgpsD0RfwMzskzQoiD1M.jpg',
  'id': 1368314,
  'title': 'Passenger',
  'original_title': 'Passenger',
  'overview': "After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.",
  'poster_path': '/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 53],
  'popularity': 38.6534,
  'release_date': '2026-05-20',
  'softcore': False,
  'video': False,
  'vote_average': 5.9,
  'vote_count': 44},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'id': 1007757,
  'title': 'Swapped',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [12, 16, 10751, 14],
  'popularity': 302.0875,
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 9.0,
  'vote_count': 1430},
 {'adult': False,
  'backdrop_path': '/6D2NsU3FIQVthPgjT6RAsX58qZ6.jpg',
  'id': 1414413,
  'title': 'Brothers Under Fire',
  'original_title': 'Brothers Under Fire',
  'overview': "Captain Jordan Wright's squadron on leave for a wedding in Mexico encounters a murderous cartel. As Jordan tries to lead survivors to safety, war erupts between his squad and the cartel, forcing him into a battle to save his men.",
  'poster_path': '/e5EKqk9V7N3w0WvYFhl6wSVrMp0.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 53, 9648, 18],
  'popularity': 40.6444,
  'release_date': '2026-04-15',
  'softcore': False,
  'video': False,
  'vote_average': 6.0,
  'vote_count': 23},
 {'adult': False,
  'backdrop_path': '/bf5TG9RODkPXmtJSgf8Iymof1wl.jpg',
  'id': 1214931,

In [15]:
data

{'page': 5,
 'results': [{'adult': False,
   'backdrop_path': '/1xV4Yv3Ma2Cu92GwT4tYUQCaEos.jpg',
   'id': 1686326,
   'title': 'Emi Martínez: The Kid Who Stops Time',
   'original_title': 'Dibu Martínez: El pibe que ataja el tiempo',
   'overview': 'Emiliano, a dreamy boy from Mar del Plata, became the ‘Dibu’ we all know today, one of the great heroes of Argentine football. Written by Hernán Casciari and directed by Gustavo Cova, it tells the story of this kid who discovers he has the power to stop time and argues with a ball that reminds him of all the challenges he has ahead. With a combination of animated sequences created by Liniers, archival footage, and interviews with his friends, family, and teammates, it is a tender and brave account of how his inner strength led him to achieve glory, becoming an inspiration for new generations.',
   'poster_path': '/yDbFSN7Jj0K4a7YFSV4OXQ4Lqhy.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [16],
   'popularity': 0.3004,
   'release_date': '2026-05-02',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/3iMoYSbI72Nwsvi7uSpqReLJVa6.jpg',
   'id': 1317288,
   'title': 'Marty Supreme',
   'original_title': 'Marty Supreme',
   'overview': 'Marty Mauser, a young man with a dream no one respects, goes to hell and back in pursuit of greatness.',
   'poster_path': '/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 53],
   'popularity': 16.2245,
   'release_date': '2025-12-19',
   'softcore': False,
   'video': False,
   'vote_average': 7.4,
   'vote_count': 1755},
  {'adult': False,
   'backdrop_path': '/vbkW4KerpshPZnP84w9qwSfYrhu.jpg',
   'id': 1198984,
   'title': 'We Bury the Dead',
   'original_title': 'We Bury the Dead',
   'overview': "After a catastrophic military disaster, the dead don't just rise - they hunt. Ava searches for her missing husband, but what she finds is far more terrifying.",
   'poster_path': '/xZqo0yPARmyF8TACVNyaOACkYWG.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 15.8781,
   'release_date': '2026-01-01',
   'softcore': False,
   'video': False,
   'vote_average': 5.993,
   'vote_count': 229},
  {'adult': False,
   'backdrop_path': '/pZixcjAW0s2dflNZGJ6zLFJuh9j.jpg',
   'id': 1594520,
   'title': 'True Justice: Eye For An Eye',
   'original_title': 'True Justice: Eye For An Eye',
   'overview': 'Amateur sleuths tackle a fresh challenge at a local school, diving into the fierce world of parent politics. Their investigation uncovers hidden agendas and unexpected alliances as they navigate the complex web within the community.',
   'poster_path': '/rcKD1DBuJzC8T35UD4KKFrXZI9n.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [80, 9648, 18, 10770],
   'popularity': 3.3139,
   'release_date': '2026-05-23',
   'softcore': False,
   'video': False,
   'vote_average': 1.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/ehozSQRKL0g0xU8NsiR1vHDudMn.jpg',
   'id': 1698856,
   'title': 'Master of the Universe',
   'original_title': 'Master of the Universe',
   'overview': 'A young man must use his untapped powers to fight back against an evil alien and their army, who will stop at nothing to take over Earth and then the universe.',
   'poster_path': '/5BoP5TmqCnbjPGf7ROYm9LdxtKw.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 878],
   'popularity': 5.2472,
   'release_date': '2026-05-22',
   'softcore': False,
   'video': False,
   'vote_average': 1.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/wns4x1GyxCudgOZRyhXKjXVJf3T.jpg',
   'id': 840464,
   'title': 'Greenland 2: Migration',
   'original_title': 'Greenland 2: Migration',
   'overview': 'Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.',
   'poster_path': '/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 53, 878],
   'popularity': 65.9617,
   'release_date': '2026-01-07',
   'softcore': False,
   'video': False,
   'vote_average': 6.41,
   'vote_count': 1113},
  {'adult': False,
   'backdrop_path': '/fe6kkxaxn0mCU2gl1vfU44IYWsy.jpg',
   'id': 1317149,
   'title': 'I Swear',
   'original_title': 'I Swear',
   'overview': 'Diagnosed with Tourette Syndrome at 15, John Davidson navigates his way against the odds through troubled teenage years and into adulthood, finding inspiration in the kindness of others to discover his true purpose in life.',
   'poster_path': '/vUwyhNWBKkSwK8ELvEeBRwV724h.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 36],
   'popularity': 13.571,
   'release_date': '2025-09-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.23,
   'vote_count': 307},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'media_type': 'movie',
   'original_language': 'ja',
   'genre_ids': [16, 28, 14],
   'popularity': 121.3106,
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 7.725,
   'vote_count': 843},
  {'adult': False,
   'backdrop_path': '/cGbPBHKSFO7hSIjxkb3KOaGdOep.jpg',
   'id': 967941,
   'title': 'Wicked: For Good',
   'original_title': 'Wicked: For Good',
   'overview': 'As an angry mob rises against the Wicked Witch, Glinda and Elphaba will need to come together one final time. With their singular friendship now the fulcrum of their futures, they will need to truly see each other, with honesty and empathy, if they are to change themselves, and all of Oz, for good.',
   'poster_path': '/si9tolnefLSUKaqQEGz1bWArOaL.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [14, 12, 10749],
   'popularity': 10.8232,
   'release_date': '2025-11-19',
   'softcore': False,
   'video': False,
   'vote_average': 6.63,
   'vote_count': 994},
  {'adult': False,
   'backdrop_path': '/s6aB9kjxNg0mu2361IkCUSpyHJV.jpg',
   'id': 639988,
   'title': 'No Other Choice',
   'original_title': '어쩔수가없다',
   'overview': 'After being laid off and humiliated by a ruthless job market, a veteran paper mill manager descends into violence in a desperate bid to reclaim his dignity.',
   'poster_path': '/sBpxTGLzKnvPSVtL5yQYpSxvKEb.jpg',
   'media_type': 'movie',
   'original_language': 'ko',
   'genre_ids': [35, 80, 53],
   'popularity': 12.8982,
   'release_date': '2025-09-24',
   'softcore': False,
   'video': False,
   'vote_average': 7.503,
   'vote_count': 1055},
  {'adult': False,
   'backdrop_path': '/u1c2DAXhpyAwFK8zljcMc4FFEc3.jpg',
   'id': 1284016,
   'title': 'Power Ballad',
   'original_title': 'Power Ballad',
   'overview': 'When Rick, a past-his-prime wedding singer, meets fading boy-band star Danny during a gig, the two bond over music and a late-night jam session. But when Danny turns one of Rick’s songs into the hit that reignites his career, Rick sets out to reclaim the recognition he believes he deserves - even if it means risking everything he cares about.',
   'poster_path': '/lsDLLagSIyTu0Gi06QjVKDp2LI2.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [35, 10402, 18],
   'popularity': 5.3831,
   'release_date': '2026-05-18',
   'softcore': False,
   'video': False,
   'vote_average': 10.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/9rsvyKSQ4y9EJNq1Rr1PR5XPjOW.jpg',
   'id': 1240889,
   'title': 'Teenage Sex and Death at Camp Miasma',
   'original_title': 'Teenage Sex and Death at Camp Miasma',
   'overview': "After years of slapdash sequels and waning fandom, the Camp Miasma slasher franchise is handed over to an enthusiastic young director for resurrection. But when she visits the original's star, a now-reclusive actress shrouded in mystery, the two women fall into a blood-soaked world of desire, fear, and delirium.",
   'poster_path': '/nLsFnXifieSTqSeWxjXSS8RvaUZ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 35],
   'popularity': 4.8754,
   'release_date': '2026-08-06',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg',
   'id': 1057265,
   'title': 'Peddi',
   'original_title': 'పెద్ది',
   'overview': 'In 1980s rural Andhra Pradesh, a spirited villager unites his community through sports to defend their pride against a powerful rival.',
   'poster_path': '/kydPBzuU4TSmDOXCkgAdVFF8sgU.jpg',
   'media_type': 'movie',
   'original_language': 'te',
   'genre_ids': [28, 18, 12],
   'popularity': 17.0177,
   'release_date': '2026-06-03',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/mmyZR5b39SoKVVnFDvn4dWbVVsh.jpg',
   'id': 1212763,
   'title': 'Evil Dead Burn',
   'original_title': 'Evil Dead Burn',
   'overview': 'After the loss of her husband, a woman seeks solace with her in-laws in their secluded family home. As one by one they are transformed into Deadites—turning the gathering into a family reunion from hell—she comes to discover that the vows she took in life... live on even in death.',
   'poster_path': '/ztadKzIIR0ERYqpHteaPFtk7inP.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27],
   'popularity': 7.0157,
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/52AkwEfQiJl2HuTPMZ2yC5Bdr9I.jpg',
   'id': 1171145,
   'title': 'Crime 101',
   'original_title': 'Crime 101',
   'overview': 'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
   'poster_path': '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [80, 53],
   'popularity': 47.8591,
   'release_date': '2026-02-11',
   'softcore': False,
   'video': False,
   'vote_average': 6.976,
   'vote_count': 1006},
  {'adult': False,
   'backdrop_path': '/enwc2Acl38mvX33QffmTzDSV89D.jpg',
   'id': 847742,
   'title': 'Drishyam 3',
   'original_title': 'ദൃശ്യം 3',
   'overview': 'To protect his family and their dark secret, Georgekutty faces an organized new threat. As walls close in and cracks widen, how much more is he willing to sacrifice ?',
   'poster_path': '/456FlpiU1iOBnaOxSd783QhZKWw.jpg',
   'media_type': 'movie',
   'original_language': 'ml',
   'genre_ids': [80, 18, 53],
   'popularity': 62.8155,
   'release_date': '2026-05-21',
   'softcore': False,
   'video': False,
   'vote_average': 6.5,
   'vote_count': 2},
  {'adult': False,
   'backdrop_path': None,
   'id': 1702750,
   'title': 'Final Broadcast',
   'original_title': 'Final Broadcast',
   'overview': 'During what appears to be the last live television broadcast before a nuclear apocalypse, a host and his crew struggle to keep the show on air as the world outside collapses.',
   'poster_path': '/ecbW1epnLqY7lgzk1hVQdfN7wT4.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [35],
   'popularity': 1.5064,
   'release_date': '2026-03-01',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/zTnAnYIn0Iv3cn0ZHlzLhou3ybm.jpg',
   'id': 1368166,
   'title': 'The Housemaid',
   'original_title': 'The Housemaid',
   'overview': 'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
   'poster_path': '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [9648, 53],
   'popularity': 70.8791,
   'release_date': '2025-12-18',
   'softcore': False,
   'video': False,
   'vote_average': 7.261,
   'vote_count': 2195},
  {'adult': False,
   'backdrop_path': '/5Q2CWHZTk48lb8QOMninYmzUfvc.jpg',
   'id': 1497348,
   'title': 'Alas Roban',
   'original_title': 'Alas Roban',
   'overview': "The lives of Sita and her daughter, Gendis, change after a terrifying night. Their journey through Alas Roban is filled with fear and relentless terror. Can they uncover what's happening there?",
   'poster_path': '/84Az3SHKRJDg971KQ0j9nZWYTcf.jpg',
   'media_type': 'movie',
   'original_language': 'id',
   'genre_ids': [18, 27, 9648],
   'popularity': 4.4661,
   'release_date': '2026-01-15',
   'softcore': False,
   'video': False,
   'vote_average': 5.0,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/hniERZojXCEc7Fp3yljZUigOAhm.jpg',
   'id': 1290417,
   'title': 'Thrash',
   'original_title': 'Thrash',
   'overview': 'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
   'poster_path': '/adk8weka3O5648g3de4z3y4aE7G.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 23.2679,
   'release_date': '2026-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 6.024,
   'vote_count': 599}],
 'total_pages': 500,
 'total_results': 10000}

In [10]:
df

,title,overview,release_date,vote_average,popularity
0,Backrooms,A strange doorway appears in the basement of a...,2026-05-27,6.000,90.5218
1,Over Your Dead Body,A dysfunctional couple head to a remote cabin ...,2026-04-24,7.400,89.0469
2,Fuze,An unexploded WWII bomb is discovered on a bus...,2026-03-23,6.510,52.0089
3,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-04-16,7.917,332.5643
4,Disclosure Day,"If you found out we weren’t alone, if someone ...",2026-06-10,0.000,30.6408
...,...,...,...,...,...
95,Drishyam 3,"To protect his family and their dark secret, G...",2026-05-21,6.500,62.8155
96,Final Broadcast,During what appears to be the last live televi...,2026-03-01,0.000,1.5064
97,The Housemaid,"Trying to escape her past, Millie Calloway acc...",2025-12-18,7.261,70.8791
98,Alas Roban,"The lives of Sita and her daughter, Gendis, ch...",2026-01-15,5.000,4.4661
99,Thrash,When a Category 5 hurricane decimates a coasta...,2026-04-10,6.024,23.2679

In [2]:
df.shape

(100, 5)

In [3]:
df.to_csv("100_movies.csv")

In [4]:
# 200 -> worked
# 404 -> unavailable
# 500 -> server down
# data = requests.get("https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd")

In [12]:

d = pd.DataFrame(data)
d.shape

(20, 4)

In [14]:
df = pd.DataFrame(data['results'])[['title','overview','release_date','vote_average','popularity']]
df

,title,overview,release_date,vote_average,popularity
0,Emi Martínez: The Kid Who Stops Time,"Emiliano, a dreamy boy from Mar del Plata, bec...",2026-05-02,0.000,0.3004
1,Marty Supreme,"Marty Mauser, a young man with a dream no one ...",2025-12-19,7.400,16.2245
2,We Bury the Dead,"After a catastrophic military disaster, the de...",2026-01-01,5.993,15.8781
3,True Justice: Eye For An Eye,Amateur sleuths tackle a fresh challenge at a ...,2026-05-23,1.000,3.3139
4,Master of the Universe,A young man must use his untapped powers to fi...,2026-05-22,1.000,5.2472
5,Greenland 2: Migration,Having found the safety of the Greenland bunke...,2026-01-07,6.410,65.9617
6,I Swear,"Diagnosed with Tourette Syndrome at 15, John D...",2025-09-22,8.230,13.5710
7,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,7.725,121.3106
8,Wicked: For Good,As an angry mob rises against the Wicked Witch...,2025-11-19,6.630,10.8232
9,No Other Choice,After being laid off and humiliated by a ruthl...,2025-09-24,7.503,12.8982
10,Power Ballad,"When Rick, a past-his-prime wedding singer, me...",2026-05-18,10.000,5.3831
11,Teenage Sex and Death at Camp Miasma,After years of slapdash sequels and waning fan...,2026-08-06,0.000,4.8754
12,Peddi,"In 1980s rural Andhra Pradesh, a spirited vill...",2026-06-03,0.000,17.0177
13,Evil Dead Burn,"After the loss of her husband, a woman seeks s...",2026-07-08,0.000,7.0157
14,Crime 101,When an elusive thief whose high-stakes heists...,2026-02-11,6.976,47.8591
15,Drishyam 3,"To protect his family and their dark secret, G...",2026-05-21,6.500,62.8155
16,Final Broadcast,During what appears to be the last live televi...,2026-03-01,0.000,1.5064
17,The Housemaid,"Trying to escape her past, Millie Calloway acc...",2025-12-18,7.261,70.8791
18,Alas Roban,"The lives of Sita and her daughter, Gendis, ch...",2026-01-15,5.000,4.4661
19,Thrash,When a Category 5 hurricane decimates a coasta...,2026-04-10,6.024,23.2679