# Fetching from TMDB website

Title, overview, release date, vote_average,popularity

In [1]:
import pandas as pd
import requests

all_movies = []

for page in range(1, 6):   # first 5 pages = 100 movies
    url = f"https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd&page={page}"
    data = requests.get(url).json()

    all_movies.extend(data["results"])

df = pd.DataFrame(all_movies)[
    ['title','overview','release_date','vote_average','popularity']
]
all_movies

[{'adult': False,
  'backdrop_path': '/diOZbaDnB2CIilwd0527AB1qMvW.jpg',
  'id': 1339713,
  'title': 'Obsession',
  'original_title': 'Obsession',
  'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
  'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 53],
  'popularity': 419.6163,
  'release_date': '2026-05-13',
  'softcore': False,
  'video': False,
  'vote_average': 7.9,
  'vote_count': 1060},
 {'adult': False,
  'backdrop_path': '/Af907x5h9W1wVis8XrSd7ynTWuy.jpg',
  'id': 1314481,
  'title': 'The Devil Wears Prada 2',
  'original_title': 'The Devil Wears Prada 2',
  'overview': "Andy Sachs returns to Runway as Miranda Priestly navigates a new media landscape and Runway's position within. The duo reconnect with former assistant Emily Charlton, now the head of a luxury brand that possesses funding which could ensure Runway's survival.",
  'poster_path': '/p35IoKfBtJDNiWJMO8ZEtIMZSfW.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 18],
  'popularity': 67.9473,
  'release_date': '2026-04-29',
  'softcore': False,
  'video': False,
  'vote_average': 6.7,
  'vote_count': 919},
 {'adult': False,
  'backdrop_path': '/54KIfdTEzOliHDKx0OkzYGqAICx.jpg',
  'id': 1081003,
  'title': 'Supergirl',
  'original_title': 'Supergirl',
  'overview': 'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
  'poster_path': '/niSvU02l2BONH9ivubV6K1a5QiK.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 12, 878],
  'popularity': 312.2982,
  'release_date': '2026-06-24',
  'softcore': False,
  'video': False,
  'vote_average': 6.204,
  'vote_count': 233},
 {'adult': False,
  'backdrop_path': '/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg',
  'id': 1315772,
  'title': 'Minions & Monsters',
  'original_title': 'Minions & Monsters',
  'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
  'poster_path': '/sO3O1szSYuXLwtkobU5TExQ6Wfa.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [12, 16, 35, 10751, 14],
  'popularity': 105.2736,
  'release_date': '2026-06-24',
  'softcore': False,
  'video': False,
  'vote_average': 6.9,
  'vote_count': 31},
 {'adult': False,
  'backdrop_path': '/oUozq2XHWifwAVOoS1qHU0qfXqM.jpg',
  'id': 1083381,
  'title': 'Backrooms',
  'original_title': 'Backrooms',
  'overview': 'A strange doorway appears in the basement of a furniture showroom.',
  'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 9648, 878],
  'popularity': 457.4145,
  'release_date': '2026-05-27',
  'softcore': False,
  'video': False,
  'vote_average': 6.858,
  'vote_count': 787},
 {'adult': False,
  'backdrop_path': '/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg',
  'id': 1084244,
  'title': 'Toy Story 5',
  'original_title': 'Toy Story 5',
  'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
  'poster_path': '/a6H2U7pjibMia41TwyFVd1PVQw3.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [16, 10751, 35, 12],
  'popularity': 555.254,
  'release_date': '2026-06-17',
  'softcore': False,
  'video': False,
  'vote_average': 7.486,
  'vote_count': 366},
 {'adult': False,
  'backdrop_path': '/qJ2KSHJhlFvASBMLbGuP7OFMaFg.jpg',
  'id': 1413976,
  'title': 'Citizen Vigilante',
  'original_title': 'Citizen Vigilante',
  'overview': 'A man takes justice into his own hands, hunting down criminals. His vigilante crusade makes him a social media star but puts him at odds with the local police chief.',
  'poster_path': '/6LmJD3Wohe0g4U62wgi7RyJqfE4.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [53, 28, 80],
  'popularity': 120.5499,
  'release_date': '2026-06-19',
  'softcore': False,
  'video': False,
  'vote_average': 6.857,
  'vote_count': 129},
 {'adult': False,
  'backdrop_path': '/t6O6XWelu27BD0OmIDCCufZZT6d.jpg',
  'id': 1301421,
  'title': 'The Sheep Detectives',
  'original_title': 'The Sheep Detectives',
  'overview': "George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.",
  'poster_path': '/iKy5460GdsoknM8ppmGlJbKxAKa.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 9648, 10751],
  'popularity': 280.7778,
  'release_date': '2026-04-30',
  'softcore': False,
  'video': False,
  'vote_average': 7.788,
  'vote_count': 527},
 {'adult': False,
  'backdrop_path': '/sbQ3laeMPGNcKoeNguC2f7rSxWT.jpg',
  'id': 1397385,
  'title': 'Little Brother',
  'original_title': 'Little Brother',
  'overview': 'A tightly wound realtor\'s picture-perfect life gets an extreme makeover when his lovably chaotic "little brother" suddenly reappears.',
  'poster_path': '/hIJpXb7Xaje2mebN9ylsS7blQzP.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35],
  'popularity': 142.1124,
  'release_date': '2026-06-18',
  'softcore': False,
  'video': False,
  'vote_average': 6.3,
  'vote_count': 119},
 {'adult': False,
  'backdrop_path': '/m3Pom6pbD51bBv3syz8NMHda3fz.jpg',
  'id': 1368337,
  'title': 'The Odyssey',
  'original_title': 'The Odyssey',
  'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
  'poster_path': '/krVa7rKCQb4OBfsr2LTJv4rTz5q.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [12, 28, 14],
  'popularity': 42.8829,
  'release_date': '2026-07-15',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
  'id': 1108427,
  'title': 'Moana',
  'original_title': 'Moana',
  'overview': "Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with the infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
  'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10751, 14, 35, 12],
  'popularity': 26.8108,
  'release_date': '2026-07-08',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/vjMvFSmGUxEtqVdaZgvFee9XkZl.jpg',
  'id': 969681,
  'title': 'Spider-Man: Brand New Day',
  'original_title': 'Spider-Man: Brand New Day',
  'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
  'poster_path': '/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 28, 12],
  'popularity': 74.8606,
  'release_date': '2026-07-29',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg',
  'id': 1284465,
  'title': 'The Death of Robin Hood',
  'original_title': 'The Death of Robin Hood',
  'overview': 'Grappling with his past after a life of crime and murder, Robin Hood finds himself gravely injured after a battle he thought would be his last. In the hands of a mysterious woman, he is offered a chance at salvation.',
  'poster_path': '/4cD7KeABHyzeJmzdA6QKe36fp2d.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [12, 18, 53, 28],
  'popularity': 31.37,
  'release_date': '2026-06-18',
  'softcore': False,
  'video': False,
  'vote_average': 6.8,
  'vote_count': 34},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'id': 936075,
  'title': 'Michael',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10402, 18],
  'popularity': 321.784,
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.7,
  'vote_count': 3159},
 {'adult': False,
  'backdrop_path': '/5k0SdQeQV2xEaGBXG1Oc8d05bkL.jpg',
  'id': 1340206,
  'title': 'Tuner',
  'original_title': 'Tuner',
  'overview': "A gifted piano tuner's meticulous skills for tuning pianos lead him to discover an unexpected aptitude for cracking safes, turning his life upside down.",
  'poster_path': '/5OvA3i9wZs5jHu0DCrfmXlzAM67.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [80, 18, 10402, 53],
  'popularity': 67.6641,
  'release_date': '2026-05-21',
  'softcore': False,
  'video': False,
  'vote_average': 7.2,
  'vote_count': 113},
 {'adult': False,
  'backdrop_path': '/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg',
  'id': 1212763,
  'title': 'Evil Dead Burn',
  'original_title': 'Evil Dead Burn',
  'overview': 'After the loss of her husband, a woman seeks solace with her in-laws. As one by one they transform into deadites, she comes to discover that the vows she took in life - survive even in death.',
  'poster_path': '/ztadKzIIR0ERYqpHteaPFtk7inP.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27, 53],
  'popularity': 20.9127,
  'release_date': '2026-07-08',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/xWBiXclrRmTggQHMRsIn84YHavs.jpg',
  'id': 1273221,
  'title': 'Scary Movie',
  'original_title': 'Scary Movie',
  'overview': "Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer's crosshairs and no horror movie IP is safe.",
  'poster_path': '/reZ8NInXjMkkaOpUHcI3Pn7iaRN.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [35, 27],
  'popularity': 411.8607,
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 5.515,
  'vote_count': 378},
 {'adult': False,
  'backdrop_path': '/piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg',
  'id': 454639,
  'title': 'Masters of the Universe',
  'original_title': 'Masters of the Universe',
  'overview': 'After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.',
  'poster_path': '/3YMd9Ogae4rDKLWuAZFuse9xhc5.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 14, 878],
  'popularity': 101.7056,
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 7.1,
  'vote_count': 339},
 {'adult': False,
  'backdrop_path': '/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg',
  'id': 1275779,
  'title': 'Disclosure Day',
  'original_title': 'Disclosure Day',
  'overview': "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.",
  'poster_path': '/AnJ8IQJI23hNpYXVNaythu061Ru.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 53],
  'popularity': 592.339,
  'release_date': '2026-06-10',
  'softcore': False,
  'video': False,
  'vote_average': 6.699,
  'vote_count': 726},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 12],
  'popularity': 129.8917,
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.692,
  'vote_count': 5488},
 {'adult': False,
  'backdrop_path': '/jmW9NkzbpI9vhyxJU2x644Nj7VU.jpg',
  'id': 1421903,
  'title': 'Werwulf',
  'original_title': 'Werwulf',
  'overview': 'England, 1305. A mute peasant cursed to become a werewolf each full moon is forced to join a royal hunting party culling the land of wolves, where he must hide his monstrous nature while seeking to break the curse before the evil within consumes his family and soul.',
  'poster_path': '/y0YXMAdeWeznRM8A8npcQZS3AMn.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [27],
  'popularity': 12.0715,
  'release_date': '2026-12-25',
  'softcore': False,
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/A2tzVTVtnTvpji96IZmleN78KKv.jpg',
  'id': 1239134,
  'title': 'Bhooth Bangla',
  'original_title': 'भूत बंगला',
  'overview': "A man inherits a palace in rural Mangalpur and plans his sister's wedding there, but strange supernatural events and panicked locals force him to investigate the property's mysterious past.",
  'poster_path': '/ArIS4vwUxdhm3j7tsTHmffdfU8W.jpg',
  'media_type': 'movie',
  'original_language': 'hi',
  'genre_ids': [27, 35],
  'popularity': 150.6479,
  'release_date': '2026-04-16',
  'softcore': False,
  'video': False,
  'vote_average': 5.463,
  'vote_count': 41},
 {'adult': False,
  'backdrop_path': '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
  'id': 83533,
  'title': 'Avatar: Fire and Ash',
  'original_title': 'Avatar: Fire and Ash',
  'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
  'poster_path': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [878, 12, 14],
  'popularity': 146.1621,
  'release_date': '2025-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 7.606,
  'vote_count': 3614},
 {'adult': False,
  'backdrop_path': '/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg',
  'id': 950028,
  'title': 'The Invite',
  'original_title': 'The Invite',
  'overview': 'Joe and Angela’s marriage is on thin ice. When they invite their enigmatic upstairs neighbors for a dinner party, the night spirals into unexpected places. Have they reignited the spark or lit the match that burns it all down?',
  'poster_path': '/b7Dr8Chzse8VagexAporUu2RtLx.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [18, 35],
  'popularity': 16.9466,
  'release_date': '2026-06-25',
  'softcore': False,
  'video': False,
  'vote_average': 8.0,
  'vote_count': 1},
 {'adult': False,
  'backdrop_path': '/laR2dpcNpbv83jdlRUNAYPPjH90.jpg',
  'id': 931285,
  'title': 'Mortal Kombat II',
  'original_title': 'Mortal Kombat II',
  'overview': 'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.',
  'poster_path': '/hwRdDFIhaEmpRgoki805YvyyjZf.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 14, 12],
  'popularity': 245.3861,
  'release_date': '2026-05-06',
  'softcore': False,
  'video': False,
  'vote_average': 7.983,
  'vote_count': 1746},
 {'adult': False,
  'backdrop_path': '/2WU6Y6aonzD6uAaCmNnEFlesxxJ.jpg',
  'id': 614945,
  'title': 'Voicemails for Isabelle',
  'original_title': 'Voicemails for Isabelle',
  'overview': "A young woman's hilariously confessional voicemails to her late sister are unknowingly redirected to a stranger, who begins to fall in love from afar.",
  'poster_path': '/canZTWSxACSnAluir3dCtMxKpA1.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [10749, 35],
  'popularity': 154.2945,
  'release_date': '2026-06-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.351,
  'vote_count': 333},
 {'adult': False,
  'backdrop_path': '/kKF4gEiBDArhONlCcunHVgBp3bA.jpg',
  'id': 1171145,
  'title': 'Crime 101',
  'original_title': 'Crime 101',
  'overview': 'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
  'poster_path': '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [80, 53],
  'popularity': 42.2128,
  'release_date': '2026-02-11',
  'softcore': False,
  'video': False,
  'vote_average': 7.0,
  'vote_count': 1117},
 {'adult': False,
  'backdrop_path': '/4lj7MZtcIDI2FmZXGkFWh0sNCsq.jpg',
  'id': 1228710,
  'title': 'The Mandalorian and Grogu',
  'original_title': 'The Mandalorian and Grogu',
  'overview': 'The evil Empire has fallen, and Imperial warlords remain scattered throughout the galaxy. As the fledgling New Republic works to protect everything the Rebellion fought for, they have enlisted the help of legendary Mandalorian bounty hunter Din Djarin and his young apprentice Grogu.',
  'poster_path': '/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg',
  'media_type': 'movie',
  'original_language': 'en',
  'genre_ids': [28, 12, 878],
  'popularity': 164.1759,
  'release_date': '2026-05-20',
  'softcore': False,
  'video': False,
  'vote_average': 6.7,
  'vote_count': 536},
 {'adult': False,
  'backdrop_path': '/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg',
  'id': 1226863,
  'title': 'The Super Mario Galaxy Movie',
  'original_title': 'The Super Mario Galaxy Movie',

In [2]:
data

{'page': 5,
 'results': [{'adult': False,
   'backdrop_path': '/jDvxsBemt2Iyslg7qn2WMzgxz23.jpg',
   'id': 1375646,
   'title': 'Colony',
   'original_title': '군체',
   'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
   'poster_path': '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg',
   'media_type': 'movie',
   'original_language': 'ko',
   'genre_ids': [28, 53, 27],
   'popularity': 38.0751,
   'release_date': '2026-05-21',
   'softcore': False,
   'video': False,
   'vote_average': 7.0,
   'vote_count': 74},
  {'adult': False,
   'backdrop_path': '/t62n8FPCo4kJZYnsxkcLojgThJF.jpg',
   'id': 1184941,
   'title': 'Blue Heron',
   'original_title': 'Blue Heron',
   'overview': "In the late 1990s, a family of six settles into their new home on Vancouver Island, as internal dynamics are slowly revealed through the experiences of the youngest child, Sasha. Their fresh start is interrupted by the increasingly dangerous behavior of Jeremy, the family's oldest child.",
   'poster_path': '/4hfMbVbYc2gsMnSE1K8Oc9LQH4j.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18],
   'popularity': 6.5495,
   'release_date': '2026-03-21',
   'softcore': False,
   'video': False,
   'vote_average': 7.1,
   'vote_count': 15},
  {'adult': False,
   'backdrop_path': '/1N5yz1IDw6Ci8le1YgeM6xtBijA.jpg',
   'id': 1358005,
   'title': 'Office Romance',
   'original_title': 'Office Romance',
   'overview': 'Jackie, President and CEO of Air Cruz, runs a tight ship in her business, including a rigid anti-fraternization policy for all her employees. When a new sexy lawyer begins working for her, that policy becomes very tested.',
   'poster_path': '/1HRUTqEVDmJC4L6tp6zd85MI6uH.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10749, 35],
   'popularity': 46.5469,
   'release_date': '2026-06-04',
   'softcore': False,
   'video': False,
   'vote_average': 6.5,
   'vote_count': 269},
  {'adult': False,
   'backdrop_path': '/ohQTIteoHPNeLd3WRlVXbCBeaN6.jpg',
   'id': 1662958,
   'title': 'Louis C.K.: Ridiculous',
   'original_title': 'Louis C.K.: Ridiculous',
   'overview': 'From a bee getting shot in New York City to paying strangers to take his aging father, Louis C.K. unleashes the ridiculous thoughts in his mind.',
   'poster_path': '/7HDsSxJ4Vve54cNmpk7Qtmai77n.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [35],
   'popularity': 0.9573,
   'release_date': '2026-06-30',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/rhuEN18ZimDOva3guaWZA4hYgLB.jpg',
   'id': 1309083,
   'title': 'Dolly',
   'original_title': 'Dolly',
   'overview': 'Young Macy is abducted by a deranged, monstrous figure who wants to raise her as its child.',
   'poster_path': '/sTPUg3XtdcKRAS5Vwsi1GYPFhNZ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27],
   'popularity': 5.0959,
   'release_date': '2026-03-06',
   'softcore': False,
   'video': False,
   'vote_average': 6.142,
   'vote_count': 81},
  {'adult': False,
   'backdrop_path': '/6tROOVmV5vRymO2g52aR8kWlfoT.jpg',
   'id': 1392469,
   'title': 'Cocktail 2',
   'original_title': 'कॉकटेल २',
   'overview': "After a decade together, Diya and Kunal's relationship is shaken when Ally, an old friend, re-enters their lives. What begins as a plan between two women spirals into chaos, triggering hilarious, emotional rollercoaster none of them saw coming.",
   'poster_path': '/oIQmtByV1LtEQSwM4EpdLTyoSlM.jpg',
   'media_type': 'movie',
   'original_language': 'hi',
   'genre_ids': [10749, 35],
   'popularity': 253.7558,
   'release_date': '2026-06-19',
   'softcore': False,
   'video': False,
   'vote_average': 5.8,
   'vote_count': 18},
  {'adult': False,
   'backdrop_path': '/cCvv1BgiBJpwaMhXhnHD3zMde79.jpg',
   'id': 1686834,
   'title': 'A Castle of Our Own',
   'original_title': 'A Castle of Our Own',
   'overview': 'When an overworked architect takes an unexpected summer trip, a sandcastle contest and a contractor help her reconnect with her daughter, rediscover joy, and find love she never saw coming.',
   'poster_path': '/mW0iFbX9JFhR8yMd8Wnu9t5cpZn.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10749, 10770],
   'popularity': 5.2967,
   'release_date': '2026-06-27',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/9UJDSMHKN1ENK9sOYf1iDghCgxo.jpg',
   'id': 1594694,
   'title': 'Lydia and the Mist Rider',
   'original_title': 'Lydia et le vaisseau des tempêtes',
   'overview': 'When her older brother Thaddeus is mysteriously kidnapped by the Spellbinder, 11-year-old Lydia sets off to find him in the Misty Sea. Picked up by the crew of a flying ship, the Dolphin, Lydia becomes the apprentice of Ambrosia, a Stargazer. Ambrosia is trying to find other children who have disappeared, including her own son. Determined to solve the mystery, Lydia must learn stargazing magic and ready herself to confront the Spellbinder.',
   'poster_path': '/olvbI4J5ikw4u3bW06Iyi9BVHoJ.jpg',
   'media_type': 'movie',
   'original_language': 'fr',
   'genre_ids': [16, 10751],
   'popularity': 4.0011,
   'release_date': '2026-02-20',
   'softcore': False,
   'video': False,
   'vote_average': 7.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/lsNYBdtXxmCjm9zZ4jrJtKmMNJZ.jpg',
   'id': 1193550,
   'title': "California Schemin'",
   'original_title': "California Schemin'",
   'overview': "In the late 1990s, Gavin Bain and Billy Boyd had their musical ambitions consistently ridiculed for having the 'wrong' accents, so they went for broke and reinvented themselves as Californian rappers. The duo re-recorded their own tracks with fake accents and turned up in London claiming to be an established duo on the Cali scene as well as childhood friends with Eminem. They quickly bagged themselves a record deal, a hefty sum in advances, and an appearance on MTV... until it all came crashing down.",
   'poster_path': '/2tYRbCPZVQD1AjZ6YGMRx71lbDU.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10402, 35, 18],
   'popularity': 1.5158,
   'release_date': '2026-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 6.0,
   'vote_count': 2},
  {'adult': False,
   'backdrop_path': '/zTnAnYIn0Iv3cn0ZHlzLhou3ybm.jpg',
   'id': 1368166,
   'title': 'The Housemaid',
   'original_title': 'The Housemaid',
   'overview': 'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
   'poster_path': '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [9648, 53],
   'popularity': 52.6043,
   'release_date': '2025-12-18',
   'softcore': False,
   'video': False,
   'vote_average': 7.263,
   'vote_count': 2520},
  {'adult': False,
   'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg',
   'id': 1523145,
   'title': 'Your Heart Will Be Broken',
   'original_title': 'Твоё сердце будет разбито',
   'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.',
   'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg',
   'media_type': 'movie',
   'original_language': 'ru',
   'genre_ids': [10749],
   'popularity': 227.0988,
   'release_date': '2026-03-26',
   'softcore': False,
   'video': False,
   'vote_average': 7.024,
   'vote_count': 106},
  {'adult': False,
   'backdrop_path': '/hO2jx1H3XafR7Y8QbFgVH1sHTY9.jpg',
   'id': 1198994,
   'title': 'Send Help',
   'original_title': 'Send Help',
   'overview': "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
   'poster_path': '/zbJWVHOtj3ljBzWgL1P8pxP03Up.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53, 35],
   'popularity': 36.3453,
   'release_date': '2026-01-22',
   'softcore': False,
   'video': False,
   'vote_average': 7.042,
   'vote_count': 1855},
  {'adult': False,
   'backdrop_path': '/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg',
   'id': 1297842,
   'title': 'GOAT',
   'original_title': 'GOAT',
   'overview': 'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.',
   'poster_path': '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [16, 35, 10751],
   'popularity': 60.7793,
   'release_date': '2026-02-11',
   'softcore': False,
   'video': False,
   'vote_average': 8.12,
   'vote_count': 853},
  {'adult': False,
   'backdrop_path': '/o6LK4vO1wvPDMvwWxZ79p04hjzC.jpg',
   'id': 1318621,
   'title': 'Descendants: Wicked Wonderland',
   'original_title': 'Descendants: Wicked Wonderland',
   'overview': 'Now that the Queen of Hearts is nice and Cinderella is safe, things seem perfect for Red and Chloe… But little do they know that changing the past created a new villain - Maddox Hatter. When Maddox captures the Queen of Hearts, Red and Chloe must work with Red’s new sister Pink, Luisa Madrigal’s son Luis and Maddox’s son Max to save her and Wonderland.',
   'poster_path': '/tPbMu1LH4YzyvG2a9X5qYERHmIv.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [14, 10751, 10770],
   'popularity': 6.0797,
   'release_date': '2026-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg',
   'id': 986056,
   'title': 'Thunderbolts*',
   'original_title': 'Thunderbolts*',
   'overview': 'After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.',
   'poster_path': '/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 878, 12],
   'popularity': 18.1537,
   'release_date': '2025-04-30',
   'softcore': False,
   'video': False,
   'vote_average': 7.292,
   'vote_count': 3611},
  {'adult': False,
   'backdrop_path': '/iZCdWpGqKQaAdhysW8gYPTdCP6A.jpg',
   'id': 1553969,
   'title': 'Sheep in the Box',
   'original_title': '箱の中の羊',
   'overview': 'Set in the near future, Otone Komoto works as an architect. She is married to Kensuke Komoto, who runs a construction company. The married couple decide to welcome a humanoid robot into their home as their son.',
   'poster_path': '/9rOCIYYT8Q76FHgl3Nm5ofuc6TQ.jpg',
   'media_type': 'movie',
   'original_language': 'ja',
   'genre_ids': [18, 878],
   'popularity': 4.8648,
   'release_date': '2026-05-29',
   'softcore': False,
   'video': False,
   'vote_average': 4.8,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/vmdt6nUXYX4mM0Ahcvh4bgHOjUt.jpg',
   'id': 1292415,
   'title': 'Beast',
   'original_title': 'Beast',
   'overview': 'MMA legend Patton James, now a commercial fisherman, is pulled back into the cage when his brother is in danger. Reuniting with his old coach Sammy, he commits to one final fight in one championship against the brutal champion Xavier Grau.',
   'poster_path': '/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 18],
   'popularity': 45.2783,
   'release_date': '2026-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 6.3,
   'vote_count': 62},
  {'adult': False,
   'backdrop_path': '/1I6QPJ2s6lch1WYO54Cv2j2Y8Z4.jpg',
   'id': 1217584,
   'title': 'Torrente for President',
   'original_title': 'Torrente Presidente',
   'overview': 'Years have passed since his last adventure, but José Luis Torrente, the most politically incorrect former cop in Spain, still sees himself as a national hero.',
   'poster_path': '/yrDKwAdZRJjoQ9RZwzRGPpMC7U1.jpg',
   'media_type': 'movie',
   'original_language': 'es',
   'genre_ids': [35],
   'popularity': 64.0669,
   'release_date': '2026-03-13',
   'softcore': False,
   'video': False,
   'vote_average': 6.068,
   'vote_count': 74},
  {'adult': False,
   'backdrop_path': '/mhXdDrphWF7XTQWyp3d8MZUqb3o.jpg',
   'id': 467905,
   'title': 'How to Make a Killing',
   'original_title': 'How to Make a Killing',
   'overview': 'Disowned at birth by his obscenely wealthy family, blue-collar Becket Redfellow will stop at nothing to reclaim his inheritance, no matter how many relatives stand in his way.',
   'poster_path': '/kw7x5mSmHhoeeqwXLwXTBsofD1N.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [35, 53],
   'popularity': 19.0269,
   'release_date': '2026-02-16',
   'softcore': False,
   'video': False,
   'vote_average': 6.975,
   'vote_count': 510},
  {'adult': False,
   'backdrop_path': '/hHDNOlATHhre4eZ7aYz5cdyJLik.jpg',
   'id': 1272837,
   'title': '28 Years Later: The Bone Temple',
   'original_title': '28 Years Later: The Bone Temple',
   'overview': "Dr. Kelson finds himself in a shocking new relationship - with consequences that could change the world as they know it - and Spike's encounter with Jimmy Crystal becomes a nightmare he can't escape.",
   'poster_path': '/kK1BGkG3KAvWB0WMV1DfOx9yTMZ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53, 878],
   'popularity': 30.3279,
   'release_date': '2026-01-14',
   'softcore': False,
   'video': False,
   'vote_average': 7.123,
   'vote_count': 1343}],
 'total_pages': 500,
 'total_results': 10000}

In [3]:
df

,title,overview,release_date,vote_average,popularity
0,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-05-13,7.900,419.6163
1,The Devil Wears Prada 2,Andy Sachs returns to Runway as Miranda Priest...,2026-04-29,6.700,67.9473
2,Supergirl,When an unexpected and ruthless adversary stri...,2026-06-24,6.204,312.2982
3,Minions & Monsters,"This is the rambunctious, ridiculous and total...",2026-06-24,6.900,105.2736
4,Backrooms,A strange doorway appears in the basement of a...,2026-05-27,6.858,457.4145
...,...,...,...,...,...
95,Sheep in the Box,"Set in the near future, Otone Komoto works as ...",2026-05-29,4.800,4.8648
96,Beast,"MMA legend Patton James, now a commercial fish...",2026-04-10,6.300,45.2783
97,Torrente for President,"Years have passed since his last adventure, bu...",2026-03-13,6.068,64.0669
98,How to Make a Killing,Disowned at birth by his obscenely wealthy fam...,2026-02-16,6.975,19.0269
99,28 Years Later: The Bone Temple,Dr. Kelson finds himself in a shocking new rel...,2026-01-14,7.123,30.3279

In [4]:
df.shape

(100, 5)

In [5]:
df.to_csv("100_movies.csv")

In [6]:
# 200 -> worked
# 404 -> unavailable
# 500 -> server down
# data = requests.get("https://api.themoviedb.org/3/trending/movie/day?api_key=5b4fa3f8fdae4392396b6d470f42d6cd")

In [7]:

d = pd.DataFrame(data)
d.shape

(20, 4)

In [8]:
d

,page,results,total_pages,total_results
0,5,"{'adult': False, 'backdrop_path': '/jDvxsBemt2...",500,10000
1,5,"{'adult': False, 'backdrop_path': '/t62n8FPCo4...",500,10000
2,5,"{'adult': False, 'backdrop_path': '/1N5yz1IDw6...",500,10000
3,5,"{'adult': False, 'backdrop_path': '/ohQTIteoHP...",500,10000
4,5,"{'adult': False, 'backdrop_path': '/rhuEN18Zim...",500,10000
5,5,"{'adult': False, 'backdrop_path': '/6tROOVmV5v...",500,10000
6,5,"{'adult': False, 'backdrop_path': '/cCvv1BgiBJ...",500,10000
7,5,"{'adult': False, 'backdrop_path': '/9UJDSMHKN1...",500,10000
8,5,"{'adult': False, 'backdrop_path': '/lsNYBdtXxm...",500,10000
9,5,"{'adult': False, 'backdrop_path': '/zTnAnYIn0I...",500,10000
10,5,"{'adult': False, 'backdrop_path': '/1x9e0qWonw...",500,10000
11,5,"{'adult': False, 'backdrop_path': '/hO2jx1H3Xa...",500,10000
12,5,"{'adult': False, 'backdrop_path': '/tq3h43fZy0...",500,10000
13,5,"{'adult': False, 'backdrop_path': '/o6LK4vO1wv...",500,10000
14,5,"{'adult': False, 'backdrop_path': '/rthMuZfFv4...",500,10000
15,5,"{'adult': False, 'backdrop_path': '/iZCdWpGqKQ...",500,10000
16,5,"{'adult': False, 'backdrop_path': '/vmdt6nUXYX...",500,10000
17,5,"{'adult': False, 'backdrop_path': '/1I6QPJ2s6l...",500,10000
18,5,"{'adult': False, 'backdrop_path': '/mhXdDrphWF...",500,10000
19,5,"{'adult': False, 'backdrop_path': '/hHDNOlATHh...",500,10000

In [ ]:
df = pd.DataFrame(data['results'])[['title','overview','release_date','vote_average','popularity']] # use these columns
df

,title,overview,release_date,vote_average,popularity
0,Colony,Professor Se-jeong is thrust into a bloody nig...,2026-05-21,7.000,38.0751
1,Blue Heron,"In the late 1990s, a family of six settles int...",2026-03-21,7.100,6.5495
2,Office Romance,"Jackie, President and CEO of Air Cruz, runs a ...",2026-06-04,6.500,46.5469
3,Louis C.K.: Ridiculous,From a bee getting shot in New York City to pa...,2026-06-30,0.000,0.9573
4,Dolly,"Young Macy is abducted by a deranged, monstrou...",2026-03-06,6.142,5.0959
5,Cocktail 2,"After a decade together, Diya and Kunal's rela...",2026-06-19,5.800,253.7558
6,A Castle of Our Own,When an overworked architect takes an unexpect...,2026-06-27,0.000,5.2967
7,Lydia and the Mist Rider,When her older brother Thaddeus is mysteriousl...,2026-02-20,7.000,4.0011
8,California Schemin',"In the late 1990s, Gavin Bain and Billy Boyd h...",2026-04-10,6.000,1.5158
9,The Housemaid,"Trying to escape her past, Millie Calloway acc...",2025-12-18,7.263,52.6043
10,Your Heart Will Be Broken,High school student Polina is saved from bully...,2026-03-26,7.024,227.0988
11,Send Help,Two colleagues become stranded on a deserted i...,2026-01-22,7.042,36.3453
12,GOAT,A small goat with big dreams gets a once-in-a-...,2026-02-11,8.120,60.7793
13,Descendants: Wicked Wonderland,Now that the Queen of Hearts is nice and Cinde...,2026-07-16,0.000,6.0797
14,Thunderbolts*,After finding themselves ensnared in a death t...,2025-04-30,7.292,18.1537
15,Sheep in the Box,"Set in the near future, Otone Komoto works as ...",2026-05-29,4.800,4.8648
16,Beast,"MMA legend Patton James, now a commercial fish...",2026-04-10,6.300,45.2783
17,Torrente for President,"Years have passed since his last adventure, bu...",2026-03-13,6.068,64.0669
18,How to Make a Killing,Disowned at birth by his obscenely wealthy fam...,2026-02-16,6.975,19.0269
19,28 Years Later: The Bone Temple,Dr. Kelson finds himself in a shocking new rel...,2026-01-14,7.123,30.3279